---
# Copyright 2017, Rackspace US, Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in witing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

server_hostname: 'loadbalancer1'
server_vm_fixed_addr: '10.0.2.150'
server_mac_address: '52:54:00:bd:80:12'

server_networks:
  dhcp:
    iface: 'eth0'
    inet_type: 'dhcp'
    vm_int_iface: vm-br-dhcp
  mgmt:
    iface: 'eth1'
    inet_type: 'static'
    address: '10.0.236.150/22'
    vm_int_iface: vm-br-eth1

