---
# Copyright 2017, Rackspace US, Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in witing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

ansible_os_family: "{{ images[default_vm_image]['image_type'] }}"

server_hostname: 'loadbalancer1'
server_domain_name: 'openstack.local'
server_vm: true
server_vm_ram: '{{ loadbalancer_vm_server_ram | default(1024) }}'
server_vm_vcpus: 1
server_vm_fixed_addr: '10.0.2.150'
server_vm_primary_network: 'dhcp'
server_image: "{{ default_vm_image }}"
server_default_interface: 'eth0'
server_mac_address: '52:54:00:bd:80:12'
server_preseed_ks: 'vm'
server_extra_options: ''

server_networks:
  dhcp:
    iface: 'eth0'
    inet_type: 'dhcp'
    vm_int_iface: vm-br-dhcp
  mgmt:
    iface: 'eth1'
    inet_type: 'static'
    address: '10.0.236.150/22'
    vm_int_iface: vm-br-eth1
  flat:
    iface: 'eth2'
    inet_type: 'static'
    address: '10.0.248.150/22'
    vm_int_iface: vm-br-eth2
  vlan:
    iface: 'eth3'
    inet_type: 'manual'
    vm_int_iface: vm-br-eth3
  vxlan:
    iface: 'eth4'
    inet_type: 'static'
    address: '10.0.240.150/22'
    vm_int_iface: vm-br-eth4
  storage:
    iface: 'eth5'
    inet_type: 'static'
    address: '10.0.244.150/22'
    vm_int_iface: vm-br-eth5
