---
# Copyright 2017, Rackspace US, Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in witing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

ansible_os_family: "{{ images[default_vm_image]['image_type'] }}"

server_domain_name: 'openstack.local'
server_vm: "{{ osa_enable_block_storage | bool }}"
server_vm_ram: '{{ cinder_vm_server_ram | default(2048) }}'
server_vm_vcpus: '{{ cinder_vm_server_vcpus | default(2) }}'
server_vm_primary_network: 'dhcp'
server_image: "{{ default_vm_image }}"
server_default_interface: 'eth0'
server_preseed_ks: 'vm'
server_extra_options: ''

default_vm_storage: "{{ cinder_vm_disk_size | default(92160) }}"
