---
# vars file for osquery (Debian specific)
# https://github.com/facebook/osquery/issues/320
# https://github.com/facebook/osquery/issues/2321

osquery_packages:
  - osquery
  - rsyslog

osquery_debug_packages:
  - osquery-dbg

_osquery_repository: "{{ osquery_repository | default('deb [arch=amd64] https://pkg.osquery.io/deb deb main') }}"
_osquery_repositorykey: "{{ osquery_repositorykey | default('1484120AC4E9F8A1A577AEEE97A80C63C9D8B80B') }}"

_osquery_auditd_pkg: "auditd"

varlog_group: syslog
varlog_mode: '0775'
