---
# https://help.ubuntu.com/lts/serverguide/apparmor.html.en

- name: Ensure apparmor packages are present
  package:
    name: "{{ item }}"
    state: present
  with_items:
    - apparmor
    - apparmor-utils
    - apparmor-profiles

- name: Ensure apparmor profile is set
  template:
    src: apparmor-usr.bin.osqueryd.j2
    dest: /etc/apparmor.d/usr.bin.osqueryd
    mode: '0600'
    owner: root
    backup: yes
  notify:
    - reload osqueryd apparmor profile

- name: Apply apparmor profile for osquery
  command: aa-complain /usr/bin/osqueryd
  failed_when: false

# Refine policy with `aa-logprof -f /var/log/syslog`
