---

- block:
    - name: systemd | check service status
      command: "systemctl status osqueryd -l"
      changed_when: false
      register: systemctl
    - debug: var=systemctl.stdout_lines
  when: ansible_service_mgr == "systemd"
- block:
    - name: service | check service status
      command: "service osqueryd status"
      changed_when: false
      register: service
    - debug: var=service.stdout_lines
  when: ansible_service_mgr != "systemd"

- block:
    - name: fallocate big file
      command: "fallocate -l {{ osquery_testing_fim_load_bigger }} /etc/testing-big-file"
      args:
        creates: /etc/testing-big-file
    - name: creation of many small files
      command: "split -b {{ osquery_testing_fim_load_smaller }} /etc/testing-big-file testing-"
      args:
        chdir: /etc
        creates: /etc/testing-big-aa
    - name: clean up
      shell: find /etc/ -name 'testing-*' -exec rm {} \;
      ignore_errors: true
# more diverse load? openssl speed, stress...
    - name: retrieve log results
      command: "{{ item }}"
      with_items:
        - head -20 /var/log/osquery/osqueryd.results.log
        - tail -20 /var/log/osquery/osqueryd.results.log
      ignore_errors: true
      changed_when: false
      register: log
  when: osquery_testing_fim_load
